return {
  { -- Highlight, edit, and navigate code
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = "BufReadPost",
    dependencies = {
      "nvim-treesitter/nvim-treesitter-textobjects",
      "nvim-treesitter/nvim-treesitter-refactor",
      {
        "nvim-treesitter/nvim-treesitter-context",
        opts = {
          max_lines = 10,
        },
      },
      "EmranMR/tree-sitter-blade",
    },
    main = "nvim-treesitter.configs",
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "diff",
        "html",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "query",
        "vim",
        "vimdoc",
        "python",
        "javascript",
        "typescript",
        "regex",
        "sql",
        "dockerfile",
        "json",
        "go",
        "gitignore",
        "graphql",
        "yaml",
        "tsx",
        "java",
        "toml",
        "ruby",
        "php",
        "html",
        "css",
        "blade",
      },
      -- Autoinstall languages that are not installed
      auto_install = true,
      highlight = {
        enable = true,
      },
      indent = { enable = true },
    },
  },
}
