return {
  ensure_installed = {
    "bash",
    "c",
    "diff",
    "html",
    "lua",
    "luadoc",
    "markdown",
    "markdown_inline",
    "query",
    "vim",
    "vimdoc",
    "python",
    "javascript",
    "typescript",
    "regex",
    "sql",
    "dockerfile",
    "json",
    "go",
    "gitignore",
    "graphql",
    "yaml",
    "tsx",
    "java",
    "toml",
    "ruby",
    "php",
    "html",
    "css",
    "blade",
  },
  -- Autoinstall languages that are not installed
  auto_install = true,
  highlight = {
    enable = true,
  },
  indent = { enable = true },
}
